### ISSUE TITLE
(VyperInstallError) Unable to install Vyper  [APE-673]

### ISSUE THREAD

**Issue by NameX44** [ApeWorX/ape-vyper#69] opened 2023-02-27 21:29 UTC
### Environment information

- `ape` and plugin versions: 
eth-ape==0.6.3
ape-vyper==0.6.1

```
ape --version

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
0.6.3
```

```
ape plugins list

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
Installed Plugins:
  vyper       0.6.1
```

- Python Version: 3.10.9
- OS: macOS

MBP M2 Pro / Ventura 13.2

### What went wrong?

When I run `ape compile`, i get the following error : 

```
ape compile

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
INFO: Compiling 'Token.vy'.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.41M/8.41M [00:02<00:00, 2.81MiB/s]
ERROR: (VyperInstallError) Unable to install Vyper version: '0.2.16'.
```

I tried to compile the brownie vyper token mix contract : [here the link](https://github.com/brownie-mix/vyper-token-mix/blob/master/contracts/Token.vy)

### How can it be fixed?

I tried to change the vyper contract version to 0.3.7, same error.

No idea at the moment i'm stuck.

thanks for your help!

**Comment by NameX44** [comment] 2023-02-28 17:31
Found that it's related to this issue : https://github.com/vyperlang/vyper/pull/2687

**Comment by unparalleled-js** [comment] 2023-03-15 21:36
I used the same versions and I was unable to reproduce, so I am not sure what to do!

I grabbed the same contract, set it to download 0.2.16 because I didn't have it yet (my 0.2 version was earlier)
So it downloaded it ad used it to compile.
I used same Python, eth-ape, and ape-vyper.

Is there anything else you would like me to try? Is there anything for `ape-vyper` we need to do or is this only a Vyper issue? If this is only a Vyper issue, can we close this?

Thank you!

**Comment by fubuloubu** [comment] 2023-03-16 15:38
> I used the same versions and I was unable to reproduce, so I am not sure what to do!
> 
> I grabbed the same contract, set it to download 0.2.16 because I didn't have it yet (my 0.2 version was earlier) So it downloaded it ad used it to compile. I used same Python, eth-ape, and ape-vyper.
> 
> Is there anything else you would like me to try? Is there anything for `ape-vyper` we need to do or is this only a Vyper issue? If this is only a Vyper issue, can we close this?
> 
> Thank you!

I think it's an issue with using macOS w/ arm64 architecture, since binaries are not published for this arch

Solution (until https://github.com/vyperlang/vyper/pull/2687 or similar is resolved) is to use x86_64 compatibility library Rosetta to use Ape

Closing with this as the solution

**Closed by fubuloubu** 2023-03-16 15:38 UTC

**Comment by charles-cooper** [comment] 2023-05-18 14:15
note: https://github.com/vyperlang/vyper/pull/2687 should be resolved now
